package com.cuemath.flashcard.deck.service;

import com.cuemath.flashcard.card.entity.Card;
import com.cuemath.flashcard.deck.entity.Deck;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Service
@Slf4j
public class FlashcardPdfService {

    private static final float PAGE_WIDTH  = PDRectangle.A4.getWidth();
    private static final float PAGE_HEIGHT = PDRectangle.A4.getHeight();
    private static final float MARGIN      = 50f;
    private static final float CONTENT_W   = PAGE_WIDTH - 2 * MARGIN;

    // Colors (RGB 0-1)
    private static final float[] NAVY   = {0.098f, 0.137f, 0.216f};
    private static final float[] RED    = {0.816f, 0.176f, 0.176f};
    private static final float[] GREEN  = {0.000f, 0.478f, 0.329f};
    private static final float[] GRAY   = {0.400f, 0.400f, 0.400f};
    private static final float[] LIGHT  = {0.957f, 0.957f, 0.961f};
    private static final float[] WHITE  = {1.000f, 1.000f, 1.000f};

    /**
     * Generate a flashcard PDF for the given deck and its cards.
     * Returns the PDF as a byte array.
     */
    public byte[] generate(Deck deck, List<Card> cards) throws IOException {
        try (PDDocument doc = new PDDocument();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            // ── Cover page ──────────────────────────────────────────────────
            addCoverPage(doc, deck, cards.size());

            // ── One card per page ────────────────────────────────────────────
            for (int i = 0; i < cards.size(); i++) {
                addCardPage(doc, cards.get(i), i + 1, cards.size());
            }

            doc.save(out);
            return out.toByteArray();
        }
    }

    // ── Cover page ───────────────────────────────────────────────────────────
    private void addCoverPage(PDDocument doc, Deck deck, int cardCount) throws IOException {
        PDPage page = new PDPage(PDRectangle.A4);
        doc.addPage(page);

        try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
            // Navy background
            cs.setNonStrokingColor(NAVY[0], NAVY[1], NAVY[2]);
            cs.addRect(0, 0, PAGE_WIDTH, PAGE_HEIGHT);
            cs.fill();

            // Red accent bar at top
            cs.setNonStrokingColor(RED[0], RED[1], RED[2]);
            cs.addRect(0, PAGE_HEIGHT - 8, PAGE_WIDTH, 8);
            cs.fill();

            // Title
            cs.setNonStrokingColor(WHITE[0], WHITE[1], WHITE[2]);
            float titleY = PAGE_HEIGHT / 2 + 60;
            drawCenteredText(cs, deck.getTitle(), PDType1Font.HELVETICA_BOLD, 28, titleY);

            // Subtitle
            cs.setNonStrokingColor(0.6f, 0.7f, 0.8f);
            drawCenteredText(cs, cardCount + " Flashcards", PDType1Font.HELVETICA, 16, titleY - 48);

            // Footer
            cs.setNonStrokingColor(0.4f, 0.5f, 0.6f);
            drawCenteredText(cs, "Generated by Flashcard Engine", PDType1Font.HELVETICA_OBLIQUE, 11, 60);
        }
    }

    // ── Card page ────────────────────────────────────────────────────────────
    private void addCardPage(PDDocument doc, Card card, int num, int total) throws IOException {
        PDPage page = new PDPage(PDRectangle.A4);
        doc.addPage(page);

        try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
            // Light background
            cs.setNonStrokingColor(LIGHT[0], LIGHT[1], LIGHT[2]);
            cs.addRect(0, 0, PAGE_WIDTH, PAGE_HEIGHT);
            cs.fill();

            // Card number badge top-right
            cs.setNonStrokingColor(NAVY[0], NAVY[1], NAVY[2]);
            String numStr = num + " / " + total;
            cs.beginText();
            cs.setFont(PDType1Font.HELVETICA_BOLD, 10);
            cs.newLineAtOffset(PAGE_WIDTH - MARGIN - 40, PAGE_HEIGHT - MARGIN + 10);
            cs.showText(numStr);
            cs.endText();

            // Category badge
            if (card.getConceptCategory() != null) {
                drawBadge(cs, card.getConceptCategory().toUpperCase(), MARGIN, PAGE_HEIGHT - MARGIN - 10);
            }

            float cardTop = PAGE_HEIGHT - MARGIN - 50;

            // ── QUESTION box ──────────────────────────────────────────────
            float qBoxH = 200;
            float qBoxY = cardTop - qBoxH;
            cs.setNonStrokingColor(WHITE[0], WHITE[1], WHITE[2]);
            drawRoundRect(cs, MARGIN, qBoxY, CONTENT_W, qBoxH);
            cs.fill();

            // "Q" label
            cs.setNonStrokingColor(RED[0], RED[1], RED[2]);
            cs.beginText();
            cs.setFont(PDType1Font.HELVETICA_BOLD, 11);
            cs.newLineAtOffset(MARGIN + 16, qBoxY + qBoxH - 24);
            cs.showText("QUESTION");
            cs.endText();

            // Red left border accent
            cs.setNonStrokingColor(RED[0], RED[1], RED[2]);
            cs.addRect(MARGIN, qBoxY, 4, qBoxH);
            cs.fill();

            // Question text
            cs.setNonStrokingColor(NAVY[0], NAVY[1], NAVY[2]);
            drawWrappedText(cs, card.getFront(), PDType1Font.HELVETICA_BOLD, 13,
                    MARGIN + 20, qBoxY + qBoxH - 48, CONTENT_W - 36, 18);

            // ── ANSWER box ───────────────────────────────────────────────
            float gap    = 16;
            float aBoxY  = qBoxY - gap - 180;
            float aBoxH  = 180;
            cs.setNonStrokingColor(WHITE[0], WHITE[1], WHITE[2]);
            drawRoundRect(cs, MARGIN, aBoxY, CONTENT_W, aBoxH);
            cs.fill();

            // "A" label
            cs.setNonStrokingColor(GREEN[0], GREEN[1], GREEN[2]);
            cs.beginText();
            cs.setFont(PDType1Font.HELVETICA_BOLD, 11);
            cs.newLineAtOffset(MARGIN + 16, aBoxY + aBoxH - 24);
            cs.showText("ANSWER");
            cs.endText();

            // Green left border accent
            cs.setNonStrokingColor(GREEN[0], GREEN[1], GREEN[2]);
            cs.addRect(MARGIN, aBoxY, 4, aBoxH);
            cs.fill();

            // Answer text
            cs.setNonStrokingColor(0.1f, 0.1f, 0.1f);
            drawWrappedText(cs, card.getBack(), PDType1Font.HELVETICA, 12,
                    MARGIN + 20, aBoxY + aBoxH - 48, CONTENT_W - 36, 17);

            // ── Concept name footer ──────────────────────────────────────
            if (card.getConceptName() != null) {
                cs.setNonStrokingColor(GRAY[0], GRAY[1], GRAY[2]);
                cs.beginText();
                cs.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
                cs.newLineAtOffset(MARGIN, MARGIN - 10);
                cs.showText("Concept: " + card.getConceptName());
                cs.endText();
            }
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private void drawCenteredText(PDPageContentStream cs, String text,
                                   PDType1Font font, float size, float y) throws IOException {
        float w = font.getStringWidth(text) / 1000 * size;
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset((PAGE_WIDTH - w) / 2, y);
        cs.showText(text);
        cs.endText();
    }

    private void drawBadge(PDPageContentStream cs, String text, float x, float y) throws IOException {
        float fontSize = 9;
        float textW = PDType1Font.HELVETICA_BOLD.getStringWidth(text) / 1000 * fontSize;
        float padX = 8, padY = 4;
        float badgeW = textW + 2 * padX;
        float badgeH = fontSize + 2 * padY;

        cs.setNonStrokingColor(NAVY[0], NAVY[1], NAVY[2]);
        cs.addRect(x, y - padY, badgeW, badgeH);
        cs.fill();

        cs.setNonStrokingColor(WHITE[0], WHITE[1], WHITE[2]);
        cs.beginText();
        cs.setFont(PDType1Font.HELVETICA_BOLD, fontSize);
        cs.newLineAtOffset(x + padX, y);
        cs.showText(text);
        cs.endText();
    }

    private void drawRoundRect(PDPageContentStream cs, float x, float y, float w, float h) throws IOException {
        // PDFBox 2.x doesn't have built-in rounded rects, use regular rect
        cs.addRect(x, y, w, h);
    }

    /**
     * Wraps text within maxWidth, drawing line by line downward from startY.
     */
    private void drawWrappedText(PDPageContentStream cs, String text,
                                  PDType1Font font, float fontSize,
                                  float startX, float startY,
                                  float maxWidth, float lineHeight) throws IOException {
        if (text == null || text.isBlank()) return;

        List<String> lines = wrapText(text, font, fontSize, maxWidth);
        cs.beginText();
        cs.setFont(font, fontSize);
        cs.newLineAtOffset(startX, startY);
        for (int i = 0; i < lines.size(); i++) {
            if (i > 0) cs.newLineAtOffset(0, -lineHeight);
            cs.showText(lines.get(i));
        }
        cs.endText();
    }

    private List<String> wrapText(String text, PDType1Font font, float fontSize, float maxWidth) throws IOException {
        List<String> lines = new ArrayList<>();
        String[] words = text.split("\\s+");
        StringBuilder current = new StringBuilder();

        for (String word : words) {
            String test = current.isEmpty() ? word : current + " " + word;
            float w = font.getStringWidth(sanitize(test)) / 1000 * fontSize;
            if (w > maxWidth && !current.isEmpty()) {
                lines.add(current.toString());
                current = new StringBuilder(word);
            } else {
                current = new StringBuilder(test);
            }
        }
        if (!current.isEmpty()) lines.add(current.toString());
        return lines;
    }

    /** Strip characters outside Latin-1 that PDType1Font can't encode */
    private String sanitize(String s) {
        if (s == null) return "";
        return s.chars()
                .filter(c -> c < 256)
                .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
                .toString();
    }
}
